# Generated by Django 4.1.2 on 2023-02-15 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_departamento_nombre_alter_municipio_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='user',
        ),
        migrations.AddField(
            model_name='foto',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.paciente'),
        ),
    ]
