# Generated by Django 4.1.2 on 2023-02-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_foto_user_foto_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto_perfil',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
