# Generated by Django 4.1.2 on 2023-02-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_paciente_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
